# Assumes `frontend` has been run. Requires a non-ssl configured nginx to be running for the domain.
- name: Ensure nginx is running
  become: yes
  service: name=nginx state=started

- name: Create https cert
  become: yes
  command: /usr/bin/certbot-auto certonly --webroot -w /home/{{user}}/{{service}}/webroot --domain {{inventory_hostname}} --agree-tos --keep-until-expiring --email {{tls_cert_email}} --quiet
  args:
    creates: /etc/letsencrypt/live/{{inventory_hostname}}/cert.pem
  notify:
    - Restart Nginx

- name: Set cron to renew certs
  become: yes
  cron: name="certbot renew" minute="27" hour="7" day="2" job="/usr/bin/certbot-auto renew >> /var/log/letsencrypt-cron.log"

- name: Set cron to reload nginx
  become: yes
  cron: name="nginx reload" minute="37" hour="7" day="2" job="/etc/init.d/nginx reload"

# Replace nginx config with SSL flavour
- name: Copy nginx config
  become: yes
  template: src=nginx/nginx.conf dest=/etc/nginx/conf.d/{{service}}.conf mode=0644 force=yes
  notify:
    - Restart Nginx
