- name: Ensure system groups exists
  become: yes
  group: name={{user}} state=present

- name: Ensure system user exists
  become: yes
  user: name={{user}} group={{user}}

- name: Create /home/{{user}}/.ssh
  become: yes
  become_user: "{{user}}"
  file: path=/home/{{user}}/.ssh state=directory

- name: Copy ssh deploy key
  become: yes
  become_user: "{{user}}"
  copy: content="{{keys.github}}" dest=/home/{{user}}/.ssh/id_rsa owner={{user}} mode=0400 force=yes
