# Required to build the meteor bundle
- name: Install g++
  become: yes
  apt: name=build-essential state=present

- name: Install Meteor
  become: yes
  shell: curl https://install.meteor.com/ | sh
  args:
    creates: /usr/local/bin/meteor
