- name: Get certbot auto
  get_url: url="https://dl.eff.org/certbot-auto" dest=/usr/bin

- name: Set certbot mode
  file: path=/usr/bin/certbot-auto mode=0755

- name: Create certs
  command: ./letsencrypt-auto certonly --standalone --agree-tos --keep-until-expiring --email {{email}} --domain {{domain}}

- name: Set cron to renew certs
  cron: name="check certs" minute="0" hour="0" job="./letsencrypt-auto renew --pre-hook 'service nginx stop' --post-hook 'service ngnix start'"
