- name: Install dependencies
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - python
    - python-dev
    - python-virtualenv
    - gcc
    - dialog
    - libaugeas0
    - libssl-dev
    - libffi-dev
    - ca-certificates
    - python-pip
    - git
    - apt-transport-https
    - ca-certificates

- name: Get certbot
  become: yes
  get_url: url="https://dl.eff.org/certbot-auto" dest=/usr/bin

- name: Set certbot mode
  become: yes
  file: path=/usr/bin/certbot-auto mode=0755

- name: Create certs
  become: yes
  command: /usr/bin/certbot-auto certonly --webroot -w /var/www/example --domain {{inventory_hostname}} --agree-tos --keep-until-expiring --email {{tls_cert_email}} --quiet

- name: Set cron to renew certs
  become: yes
  cron: name="check certs" minute="0" hour="0" job="/user/bin/certbot-auto renew"
